### ISSUE TITLE
ConvModule' object has no attribute 'weight',

### ISSUE THREAD

**Issue by Alexwong-1024** [ShichengMiao16/MADet#1]
Please tell me, I use the be command python tools/train.py configs/madet/madet_r101_fpn_1x_coco.py for training, but an error like this occurs, nexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
  File "tools/train.py", line 185, in <module>
    main()
  File "tools/train.py", line 158, in main
    model = build_detector(
  File "/root/autodl-tmp/MADet/mmdet/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/root/autodl-tmp/MADet/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/root/autodl-tmp/MADet/mmdet/models/detectors/madet.py", line 18, in __init__
    super(MADet, self).__init__(backbone, neck, bbox_head, train_cfg,
  File "/root/autodl-tmp/MADet/mmdet/models/detectors/single_stage.py", line 33, in __init__
    self.init_weights(pretrained=pretrained)
  File "/root/autodl-tmp/MADet/mmdet/models/detectors/single_stage.py", line 50, in init_weights
    self.bbox_head.init_weights()
  File "/root/autodl-tmp/MADet/mmdet/models/dense_heads/madet_head.py", line 177, in init_weights
    normal_init(self.dcn, std=0.01)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 24, in normal_init
    nn.init.normal_(module.weight, mean, std)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'ConvModule' object has no attribute 'weight', looking forward to your reply.

**Comment by ShichengMiao16** [comment]
Please check that the versions of your installed packages are consistent with those in the INSTALL instruction file. 
---- Replied Message ----
| From | ***@***.***> |
| Date | 11/06/2023 20:41 |
| To | ShichengMiao16/MADet ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [ShichengMiao16/MADet] ConvModule' object has no attribute 'weight', (Issue #1) |

Please tell me, I use the be command python tools/train.py configs/madet/madet_r101_fpn_1x_coco.py for training, but an error like this occurs, nexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
File "tools/train.py", line 185, in
main()
File "tools/train.py", line 158, in main
model = build_detector(
File "/root/autodl-tmp/MADet/mmdet/models/builder.py", line 67, in build_detector
return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
File "/root/autodl-tmp/MADet/mmdet/models/builder.py", line 32, in build
return build_from_cfg(cfg, registry, default_args)
File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
return obj_cls(**args)
File "/root/autodl-tmp/MADet/mmdet/models/detectors/madet.py", line 18, in init
super(MADet, self).init(backbone, neck, bbox_head, train_cfg,
File "/root/autodl-tmp/MADet/mmdet/models/detectors/single_stage.py", line 33, in init
self.init_weights(pretrained=pretrained)
File "/root/autodl-tmp/MADet/mmdet/models/detectors/single_stage.py", line 50, in init_weights
self.bbox_head.init_weights()
File "/root/autodl-tmp/MADet/mmdet/models/dense_heads/madet_head.py", line 177, in init_weights
normal_init(self.dcn, std=0.01)
File "/root/miniconda3/lib/python3.8/site-packages/mmcv/cnn/utils/weight_init.py", line 24, in normal_init
nn.init.normal_(module.weight, mean, std)
File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 771, in getattr
raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'ConvModule' object has no attribute 'weight', looking forward to your reply.

**Comment by Alexwong-1024** [comment]
Thanks for the quick reply, I'll give it a try.

**Comment by zhihuizhang628** [comment]
> Thanks for the quick reply, I'll give it a try.

Hello, I encountered the same problem as you. How did you solve it? Can you provide specific methods or commands?

**Comment by abcde-bit** [comment]
> > Thanks for the quick reply, I'll give it a try.
> 
> Hello, I encountered the same problem as you. How did you solve it? Can you provide specific methods or commands?

Hello,brother.I also encountered the same problem as you. Is it a problem with CUDA and Pytorch versions? Did you install CUDA9.2 and pytorch 1.3.1.

**Comment by kelesyhund** [comment]
您好，我也遇到了同样的问题，请问您是如何解决的

**Comment by wap1024** [comment]
> 您好，我也遇到了同样的问题，请问您是如何解决的

安装的版本问题，最好按照作者的版本去安装。
